export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_ITEM_REQUEST = 'CART_ITEM_REQUEST'
export const CART_ITEM_SUCCESS = 'CART_ITEM_SUCCESS'
export const CART_ITEM_FAILURE = 'CART_ITEM_FAILURE'