# Generated by Django 4.1.7 on 2023-03-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_shippingaddress_order_order_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='state',
        ),
    ]
